# Docker environment configuration
spring:
  profiles:
    active: docker
  
  # Database Configuration for Docker
  datasource:
    url: jdbc:postgresql://postgres:5432/taskboard
    username: ${DATABASE_USERNAME:-taskboard_user}
    password: ${DATABASE_PASSWORD:-taskboard_password}
  
  # Redis Configuration for Docker
  data:
    redis:
      host: redis
      port: 6379
  
  # Kafka Configuration for Docker
  kafka:
    bootstrap-servers: kafka:29092

# Service URLs for Docker environment
service:
  urls:
    user-service: http://user-service:8080
    task-service: http://task-service:8080
    project-service: http://project-service:8080
    time-service: http://time-service:8080
    analytics-service: http://analytics-service:8080
    notification-service: http://notification-service:8080
    search-service: http://search-service:8080
    file-service: http://file-service:8080
    gateway-service: http://kong:8000

# External Services for Docker
external:
  services:
    prometheus: http://prometheus:9090
    jaeger: http://jaeger:14268
    kafka-ui: http://kafka-ui:8080
    grafana: http://grafana:3000

