# Kubernetes environment configuration
spring:
  profiles:
    active: kubernetes
  
  # Database Configuration for Kubernetes
  datasource:
    url: jdbc:postgresql://postgres-service:5432/taskboard
    username: taskboard_user
    password: ${DATABASE_PASSWORD}
  
  # Redis Configuration for Kubernetes
  data:
    redis:
      host: redis-service
      port: 6379
  
  # Kafka Configuration for Kubernetes
  kafka:
    bootstrap-servers: kafka-service:9092

# Service URLs for Kubernetes environment
service:
  urls:
    user-service: http://user-service:8080
    task-service: http://task-service:8080
    project-service: http://project-service:8080
    time-service: http://time-service:8080
    analytics-service: http://analytics-service:8080
    notification-service: http://notification-service:8080
    search-service: http://search-service:8080
    file-service: http://file-service:8080
    gateway-service: http://kong-service:8000

# External Services for Kubernetes
external:
  services:
    prometheus: http://prometheus-service:9090
    jaeger: http://jaeger-service:14268
    kafka-ui: http://kafka-ui-service:8080
    grafana: http://grafana-service:3000

