apiVersion: v1
kind: ConfigMap
metadata:
  name: taskboard-config
  namespace: taskboard-microservices
data:
  # Database Configuration
  DATABASE_URL: "jdbc:postgresql://postgres-service:5432/taskboard"
  DATABASE_USERNAME: "taskboard_user"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8080"
  TASK_SERVICE_URL: "http://task-service:8080"
  PROJECT_SERVICE_URL: "http://project-service:8080"
  TIME_SERVICE_URL: "http://time-service:8080"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8080"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8080"
  SEARCH_SERVICE_URL: "http://search-service:8080"
  FILE_SERVICE_URL: "http://file-service:8080"
  
  # Monitoring
  PROMETHEUS_URL: "http://prometheus-service:9090"
  JAEGER_URL: "http://jaeger-service:14268"
  
  # Application Properties
  SPRING_PROFILES_ACTIVE: "kubernetes"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_TASKBOARD: "DEBUG"
