apiVersion: v1
kind: ConfigMap
metadata:
  name: taskboard-config
  namespace: taskboard
data:
  # Database Configuration
  DATABASE_URL: "jdbc:postgresql://postgres-service:5432/taskboard"
  DATABASE_USERNAME: "taskboard"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8080"
  TASK_SERVICE_URL: "http://task-service:8080"
  PROJECT_SERVICE_URL: "http://project-service:8080"
  TIME_SERVICE_URL: "http://time-service:8080"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8080"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8080"
  SEARCH_SERVICE_URL: "http://search-service:8080"
  FILE_SERVICE_URL: "http://file-service:8080"
  GATEWAY_SERVICE_URL: "http://gateway-service:8000"
  
  # External Services
  PROMETHEUS_URL: "http://prometheus-service:9090"
  JAEGER_URL: "http://jaeger-service:16686"
  KAFKA_UI_URL: "http://kafka-ui-service:8080"
  GRAFANA_URL: "http://grafana-service:3000"
  KIBANA_URL: "http://kibana-service:5601"
  MINIO_URL: "http://minio-service:9000"
  
  # Monitoring
  JAEGER_ENDPOINT: "http://jaeger-service:14268/api/traces"
  
  # Feature Flags
  ENABLE_CACHING: "true"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  ENABLE_SECURITY: "true"
  
  # Logging
  LOG_LEVEL: "INFO"
  LOG_FILE_PATH: "logs/"
  
  # Performance
  MAX_CONNECTIONS: "100"
  CONNECTION_TIMEOUT: "30000"
  READ_TIMEOUT: "30000"
  WRITE_TIMEOUT: "30000"
  
  # Security
  BCRYPT_ROUNDS: "12"
  SESSION_TIMEOUT: "3600"
  MAX_LOGIN_ATTEMPTS: "5"
  LOCKOUT_DURATION: "300"
  
  # File Storage
  MAX_FILE_SIZE: "10485760"
  ALLOWED_FILE_TYPES: "jpg,jpeg,png,gif,pdf,doc,docx,txt"
  UPLOAD_PATH: "/uploads"