apiVersion: v1
kind: ConfigMap
metadata:
  name: taskboard-config
  namespace: taskboard-microservices
data:
  # Database Configuration
  DATABASE_URL: "jdbc:postgresql://postgres-service:5432/taskboard"
  DATABASE_USERNAME: "taskboard_user"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_CONSUMER_GROUP: "taskboard-group"
  
  # Service Configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8080"
  SERVER_CONTEXT_PATH: ""
  
  # Service URLs (for inter-service communication)
  USER_SERVICE_URL: "http://user-service:8080"
  TASK_SERVICE_URL: "http://task-service:8080"
  PROJECT_SERVICE_URL: "http://project-service:8080"
  TIME_SERVICE_URL: "http://time-service:8080"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8080"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8080"
  SEARCH_SERVICE_URL: "http://search-service:8080"
  FILE_SERVICE_URL: "http://file-service:8080"
  GATEWAY_SERVICE_URL: "http://kong-service:8000"
  
  # External Services
  PROMETHEUS_URL: "http://prometheus-service:9090"
  JAEGER_URL: "http://jaeger-service:14268"
  KAFKA_UI_URL: "http://kafka-ui-service:8080"
  GRAFANA_URL: "http://grafana-service:3000"
  
  # Actuator Configuration
  ACTUATOR_BASE_PATH: "/actuator"
  ACTUATOR_ENDPOINTS: "health,info,metrics,prometheus"
  ACTUATOR_HEALTH_DETAILS: "always"
  ACTUATOR_HEALTH_COMPONENTS: "always"
  
  # Logging Configuration
  LOG_LEVEL_ROOT: "INFO"
  LOG_LEVEL_TASKBOARD: "DEBUG"
  LOG_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  LOG_PATTERN_FILE: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  # JPA Configuration
  JPA_DDL_AUTO: "update"
  JPA_SHOW_SQL: "false"
  
  # Monitoring Configuration
  PROMETHEUS_ENABLED: "true"
