apiVersion: v1
kind: Secret
metadata:
  name: taskboard-secrets
  namespace: taskboard-microservices
  labels:
    app: taskboard
    component: secrets
type: Opaque
data:
  # Base64 encoded values
  # To encode: echo -n "your-password" | base64
  # IMPORTANT: Change these values in production!
  DATABASE_PASSWORD: dGFza2JvYXJkX3N1cGVyX3NlY3VyZV9wYXNzd29yZF8yMDI0  # taskboard_super_secure_password_2024
  JWT_SECRET: dGFza2JvYXJkX3N1cGVyX3NlY3VyZV9qd3Rfc2VjcmV0X2tleV8yMDI0XzY0Y2hhcnM=  # taskboard_super_secure_jwt_secret_key_2024_64chars
  REDIS_PASSWORD: dGFza2JvYXJkX3JlZGlzX3NlY3VyZV9wYXNzd29yZA==  # taskboard_redis_secure_password
  KAFKA_PASSWORD: dGFza2JvYXJkX2thZmthX3NlY3VyZV9wYXNzd29yZA==  # taskboard_kafka_secure_password
  ENCRYPTION_KEY: dGFza2JvYXJkX2VuY3J5cHRpb25fa2V5XzMyY2hhcmFjdGVycw==  # taskboard_encryption_key_32characters
  API_KEY: dGFza2JvYXJkX2FwaV9rZXlfMjAyNF9zZWN1cmU=  # taskboard_api_key_2024_secure

