apiVersion: v1
kind: Secret
metadata:
  name: taskboard-secrets
  namespace: taskboard
type: Opaque
data:
  # Database Password (base64 encoded)
  DATABASE_PASSWORD: dGFza2JvYXJk  # taskboard
  
  # Redis Password (base64 encoded)
  REDIS_PASSWORD: ""  # Empty for now
  
  # JWT Secret (base64 encoded)
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJlLW11c3QtYmUtYXQtbGVhc3QtMzItY2hhcmFjdGVycw==  # your-super-secret-jwt-key-here-must-be-at-least-32-characters
  
  # CORS Configuration
  CORS_ALLOWED_ORIGINS: aHR0cDovL2xvY2FsaG9zdDo0MjAwLGh0dHA6Ly9sb2NhbGhvc3Q6MzAwMA==  # http://localhost:4200,http://localhost:3000
  
  # Email Configuration
  SMTP_USERNAME: eW91ci1lbWFpbEBnbWFpbC5jb20=  # your-email@gmail.com
  SMTP_PASSWORD: eW91ci1hcHAtcGFzc3dvcmQ=  # your-app-password
  
  # SMS Configuration
  SMS_API_KEY: eW91ci1zbXMtYXBpLWtleQ==  # your-sms-api-key
  
  # Push Notifications
  FCM_SERVER_KEY: eW91ci1mY20tc2VydmVyLWtleQ==  # your-fcm-server-key
  APNS_KEY_ID: eW91ci1hcG5zLWtleS1pZA==  # your-apns-key-id
  APNS_TEAM_ID: eW91ci1hcG5zLXRlYW0taWQ=  # your-apns-team-id
  APNS_BUNDLE_ID: Y29tLnRhc2tib2FyZC5hcHA=  # com.taskboard.app