#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Запуск pre-commit проверок..."

# Lint staged files
npx lint-staged

# Проверка TypeScript типов
npm run build -- --configuration=development --no-emit

echo "✅ Pre-commit проверки завершены!"